# Generated by Django 5.2.6 on 2025-12-02 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habitcompletionmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)]),
        ),
    ]
