# Generated by Django 5.2.6 on 2025-12-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habitmodel_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitmodel',
            name='success_rate',
        ),
        migrations.RemoveField(
            model_name='habitmodel',
            name='total_time_minutes',
        ),
    ]
